Feat: add windows linters and testing

diff --git a/.github/workflows/lint_test_windows.yml b/.github/workflows/lint_test_windows.yml
--- a/.github/workflows/lint_test_windows.yml
+++ b/.github/workflows/lint_test_windows.yml
@@ -23,34 +23,33 @@ jobs:
           cmake .. -A x64 -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_BUILD_TYPE=Debug
           cmake --build . --config Debug -j 4
 
-#
-#      - name: Run linters
-#        uses: cpp-linter/cpp-linter-action@v2
-#        id: linter
-#        env:
-#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-#        with:
-#          style: file
-#          version: 16
-#          repo-root: "Team11\Code11"
-#          database: "build\compile_commands.json"
-#          ignore: "build | lib | cmake | src\autotester_gui | src\unit_testing | src\integration_testing"
-#          files-changed-only: false
-#          tidy-checks: "-*"
-#          step-summary: true
-#
-#      - name: Check linter status
-#        if: steps.linter.outputs.clang-format-checks-failed > 0
-#        run: echo "Some files failed the linting checks!" && exit 1
-#
-#      - name: Run Unit Test
-#        run: |
-#          .\Team11\Code11\build\src\unit_testing\unit_testing.exe
-#
-#      - name: Run Integration Test
-#        run: |
-#          .\Team11\Code11\build\src\integration_testing\integration_testing.exe
-#
+      - name: Run linters
+        uses: cpp-linter/cpp-linter-action@v2
+        id: linter
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          style: file
+          version: 16
+          repo-root: "Team11/Code11"
+          database: "build/compile_commands.json"
+          ignore: "build | lib | cmake | src/autotester_gui | src/unit_testing | src/integration_testing"
+          files-changed-only: false
+          tidy-checks: "-*"
+          step-summary: true
+
+      - name: Check linter status
+        if: steps.linter.outputs.clang-format-checks-failed > 0
+        shell: bash
+        run: echo "Some files failed the linting checks!" && exit 1
+
+      - name: Run Unit Test
+        shell: bash
+        run: ./Team11/Code11/build/src/unit_testing/unit_testing.exe
+
+      - name: Run Integration Test
+        run: ./Team11/Code11/build/src/integration_testing/integration_testing.exe
+
 #      - name: Setup Python
 #        uses: actions/setup-python@v2
 #        with:
